server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

spring:
  config:
    import: optional:C:/java/workspace/study/config/config.yml
  mvc:
      servlet:
        path: /
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
      static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true

#logging:
#  config: logback/logback.xml